version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: aftas
    ports:
        - "5432:5432"

  spring-app:
    build:
      context: ./AFTAS
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aftas?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  spring-app-angular:
    build:
      context: ./Aftas-Angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-app
